[tool.poetry]
name = "charmonium.time_block"
version = "1.0.0"
description = "Time a block of code."
authors = ["Samuel Grayson <sam+dev@samgrayson.me>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/charmoniumQ/charmonium.time_block.git"
packages = [
    { include = "charmonium" },
]

[tool.poetry.scripts]
time_block = "charmonium.time_block._cli:main"

[tool.poetry.dependencies]
python = "^3.12"
humanize = "^4.15.0"
psutil = "^7.0"
wrapt = "^1"

[tool.poetry.group.dev.dependencies]
coverage = "^7.10.4"
mypy = "^1.17.1"
pytest = "^8.4.1"
pytest-asyncio = "^1.1.0"
types-psutil = "^7.0.0.20250801"
twine = "^6.1.0"

[tool.pytest.ini_options]
addopts = "--doctest-glob='*.rst' -W error"
asyncio_default_fixture_loop_scope = "session"

[[tool.bumpversion.file]]
path = "pyproject.toml"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
