on:
  push:
    branches: [master, add-ci]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # using pyenv to install multiple Python versions on the same instance is more efficient than a build matrix
      - uses: gabrielfalcao/pyenv-action@v6

      - run: |
          pyenv install --list

      - run: |
          cd "${GITHUB_WORKSPACE}"
          python -m pip install tox
          tox
