on:
  push:
    branches: [master, add-ci]
  pull_request:
    branches: [master]

env:
  python_versions: 3.6.10 3.7.7 3.8.2
  # Installs the same versions as in Tox

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # using pyenv to install multiple Python versions on the same instance is more efficient than a build matrix
      - uses: gabrielfalcao/pyenv-action@v6
        id: install_pyenv

      - uses: actions/cache@v2
        with:
          path: ${{ steps.install_pyenv.outputs.pyenv_root }}
          key: ${{ env.python_versions }}

      - run: |
          pyenv install ${python_versions}

      - run: |
          cd "${GITHUB_WORKSPACE}"
          python -m pip install tox
          tox
